# Generated by Django 6.1 on 2026-09-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kategoritë',
            },
        ),
        migrations.CreateModel(
            name='Artikull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=200)),
                ('permbajtja', models.TextField()),
                ('data_publikimit', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='lajmet/')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lajmet.kategoria')),
            ],
            options={
                'verbose_name_plural': 'Artikujt',
            },
        ),
    ]
