# Generated by Django 6.1 on 2026-09-01 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=80)),
                ('teksti', models.TextField()),
                ('data_krijimit', models.DateTimeField(auto_now_add=True)),
                ('artikulli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentet', to='lajmet.artikull')),
            ],
            options={
                'verbose_name_plural': 'Komentet',
            },
        ),
    ]
