# Generated by Django 6.1 on 2026-09-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0002_koment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koment',
            options={},
        ),
        migrations.RenameField(
            model_name='koment',
            old_name='data_krijimit',
            new_name='data_publikimit',
        ),
        migrations.RenameField(
            model_name='koment',
            old_name='teksti',
            new_name='permbajtja',
        ),
        migrations.AlterField(
            model_name='koment',
            name='emri',
            field=models.CharField(blank=True, default='Anonim', max_length=100, null=True),
        ),
    ]
