# Generated by Django 6.1 on 2026-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0004_koment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikull',
            name='shikime',
            field=models.PositiveIntegerField(default=0, verbose_name='Numri i shikimeve'),
        ),
    ]
