# Generated by Django 6.1 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0005_artikull_shikime'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikull',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Shkruaj vetëm ID-në e videos (p.sh. për linkun https://www.youtube.com/watch?v=dQw4w9WgXcQ vendos vetëm dQw4w9WgXcQ)', max_length=50, null=True, verbose_name='YouTube Video ID'),
        ),
    ]
