# Generated by Django 6.1 on 2026-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0006_artikull_youtube_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=200, verbose_name='Titulli i Videos')),
                ('youtube_id', models.CharField(max_length=100, verbose_name='YouTube Video ID ose Link')),
                ('data_publikimit', models.DateTimeField(auto_now_add=True, verbose_name='Data e Publikimit')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videot',
                'ordering': ['-data_publikimit'],
            },
        ),
    ]
