# Generated by Django 6.1 on 2026-09-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(help_text='Mund të vendosni vetëm ID-në ose të gjithë linkun e YouTube.', max_length=100, verbose_name='YouTube Video ID ose Link'),
        ),
    ]
