# Generated by Django 6.1 on 2026-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0008_alter_video_youtube_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100, verbose_name='Emri i Reklamës / Klientit')),
                ('imazhi', models.ImageField(upload_to='reklama/', verbose_name='Foto Banneri')),
                ('linku', models.URLField(verbose_name='Linku i Destinacionit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivizo Reklamën')),
                ('data_krijimit', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklamë',
                'verbose_name_plural': 'Reklumat',
            },
        ),
    ]
