# Generated by Django 6.1 on 2026-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0009_reklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onesignal_player_id', models.CharField(max_length=255, unique=True, verbose_name='OneSignal Player ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e regjistrimit')),
            ],
            options={
                'verbose_name': 'Abonim Njoftimesh',
                'verbose_name_plural': 'Abonimet e Njoftimeve',
            },
        ),
    ]
