# Generated by Django 6.1 on 2026-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0010_pushnotificationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Endpoint URL')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256DH Key')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Regjistrimit')),
            ],
            options={
                'verbose_name': 'Abonim Njoftimesh',
                'verbose_name_plural': 'Abonimet e Njoftimeve',
            },
        ),
        migrations.DeleteModel(
            name='PushNotificationSubscription',
        ),
    ]
