# Generated by Django 6.1 on 2026-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0011_pushsubscription_delete_pushnotificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikull',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
