# Generated by Django 6.1 on 2026-09-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajmet', '0013_auto_20260908_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikull',
            name='shikime',
        ),
        migrations.AddField(
            model_name='artikull',
            name='eshte_premium',
            field=models.BooleanField(default=False, help_text="Zgjidhni nëse ky artikull kërkon abonim/pagesë për t'u lexuar plotësisht.", verbose_name='Artikull Premium (Paywall)'),
        ),
    ]
