"""
Django settings for portal_lajmesh project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path
import urllib.parse
import dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ngarko variablat e mjedisit nga skedari .env lokal
dotenv.load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-r$7yl-hhc&3d*l@4k^k*i(g-h817(2_a!uk457=v%=d5mb-*b7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('RENDER', '') == ''

# Lejon Render dhe çdo host tjetër të hyjë në faqe
ALLOWED_HOSTS = ['*']

# Lejon përdorimin e CSRF në Render (për format dhe admin panelin)
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  # Duhet të jetë PARA staticfiles
    'django.contrib.staticfiles',
    'cloudinary',
    'lajmet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise direkt pas SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portal_lajmesh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'lajmet.context_processors.kategorite_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_lajmesh.wsgi.application'


# Database
DATABASE_URL = os.environ.get('DATABASE_URL')

# Lidhja me PostgreSQL bëhet vetëm në Render (kur DEBUG = False)
# Lokalisht (kur DEBUG = True) do të përdoret gjithmonë SQLite3
if DATABASE_URL and not DEBUG:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'sq'

TIME_ZONE = 'Europe/Tirane'

USE_I18N = True

USE_TZ = True


# Static Files (CSS, JS)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


# Media Files (Cloudinary)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Konfigurimi i Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'oornuwp6',
    'API_KEY': '975767264233752',
    'API_SECRET': 'iis2W8k6iKbS6Uvb_Fz6Qkk3bZ8'
}

# Parandalon dështimin e WhiteNoise nëse mungon ndonjë skedar statik
WHITENOISE_MANIFEST_STRICT = False

# Konfigurimi i Storages sipas mjedisit (Django 4.2+)
if DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

# Përputhshmëria me pakot që kërkojnë variablën e vjetër
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'